### ISSUE TITLE
Video's unavailable for download

### ISSUE THREAD

**Issue by PantherStyle** [robwebset/screensaver.video#3]
Hi. As I'm sure you know, when a user tries to download one of the 'built-in' videos (which are all excellent by the way), we get a message explaining that you no longer have somewhere to host the source files. 

I'm new to github, so this is the only way I could think to contact you. I would be interested in helping out in some way (I can make sufficient space on my personal synology NAS, though I'm sure my upload speeds would not be sufficient for any more than 1 user at a time. 

I am also trying to drum up support from some others, so may be able to find someone with a higher bandwidth solution. In any case, I'd be interested in providing an 'offsite backup' for the videos until something more permanent is put in place. 

Let me know your thoughts.

**Comment by robwebset** [comment]
No problem contacting me like this (in fact I think it's the only way at the moment).

Thanks for your offer - I do actually have a few backups of the videos, and I tend to agree with you - local NAS would kill your bandwidth if people started downloading them. (Which is why I've not made them available directly from my home server - in addition to my very very slow broadband).

Thanks
Rob

**Comment by PantherStyle** [comment]
Yeah OK.

Have you tried http://www.filehosting.org/ ?
It claims to have unlimited file hosting for free. Might be worth trying.

**Comment by robwebset** [comment]
Thanks for the suggestion - I've looked at a lot of these sorts of sites in the past and they each have their own issues - no direct download, filesize limits, files "expiring" after a number of days (20 days for filehosting.org).

Thanks
Rob
